spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_udemy
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      show_sql: false
    open-in-view: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html